language: ruby
script: bundle exec rake test_$DB
rvm:
  - jruby-18mode
  - jruby-19mode
env:
  - DB=mysql
  - DB=postgresql
  - DB=h2
  - DB=hsqldb
  - DB=sqlite3
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  allow_failures:
    - gemfiles/rails23.gemfile
branches:
  only:
    - master
