language: ruby
sudo: false
bundler_args: --without development
script: bundle exec rake test_$DB
before_script:
  - export JRUBY_OPTS="--server" # -Xcompile.invokedynamic=false
before_install:
  - ((jruby -v | grep 1.8.7) && jruby --1.9 -S gem update --system 2.1.11) || true
rvm:
  - jruby-1.7.18
  #- jruby-head # 9000 ignores --1.8 and --1.9 switches
jdk:
  - openjdk6
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
env:
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=false
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=true
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true INSERT_RETURNING=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=sqlite3
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=derby PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=h2 PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=hsqldb PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=jndi PREPARED_STATEMENTS=true
  - JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
  - JRUBY_OPTS="--1.9 $JRUBY_OPTS" DB=jdbc PREPARED_STATEMENTS=true
branches:
  only:
    - master
    - /.*-stable$/
    - /^test-.*/
matrix:
  allow_failures:
    - gemfile: gemfiles/rails42.gemfile
  exclude:
    # Rails 4 prefers Ruby 2.0 (or at least >= 1.9.3) :
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 4.1 does not support Ruby 1.8 :
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 4.2 will not support Ruby 1.8 :
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    ## JRuby 9K :
    # Rails 2.3 (JRuby 9K) NOTE we should exclude all :
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 3.0 (JRuby 9K) NOTE we should exclude all :
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 3.1 (JRuby 9K) NOTE we should exclude all :
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 3.2 (JRuby 9K) :
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 4.0 (JRuby 9K) :
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 4.1 (JRuby 9K) :
    - rvm: jruby-head
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-1.7.18
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
    # Rails 4.2 (JRuby 9K) :
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=mysql
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=postgresql
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=sqlite3
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=derby
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=h2
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=hsqldb
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jndi
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="--1.8 $JRUBY_OPTS" DB=jdbc
